### ISSUE TITLE
Your Photo Here

### ISSUE THREAD

**Issue by zornfett** [higherdotteam/kidbank#2]
What's the happs with the 'Your Photo Here' issue? what photo should be in there and is this to be populated by javascript (or is this simply not implemented yet)?

**Comment by andrewarrow** [comment]
that's a request for HDT students that want their picture there. Go for it. Push some new html with your pic and bio if u want to be listed in the about us page.

**Comment by andrewarrow** [comment]
@chrismomdjian fixed this one but everyone is welcome to add their pic and bio
