### ISSUE TITLE
First and Last name changes not saving

### ISSUE THREAD

**Issue by versionalt** [higherdotteam/kidbank#3]
- My original name is `John Doe`. 

- I want to change my name to `Jo Do`.
![image](https://cloud.githubusercontent.com/assets/12492121/22906542/ecf7e002-f212-11e6-97cb-d38f47499a4e.png)

- After clicking save, and receiving confirmation of `saved changes`, my name is still `John Doe`.
![image](https://cloud.githubusercontent.com/assets/12492121/22906561/010796c8-f213-11e6-8057-fda967c39613.png)

**Comment by andrewarrow** [comment]
thanks, I'll look at that.
